:Author: serhatzorlu
:Email:
:Date: 20/05/2024
:Revision: version#
:License: Public Domain

= Project: {Project}

The Easy Park project uses an Android app and Internet of Things (IoT) to make it easier to discover parking spaces. The system delivers real-time updates on parking availability through the use of sensors and LEDs.

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open EasyPark.ino file
2. Download
3. Create a dashboard on the Arduino Cloud and link the variable in code

== Step 2: Assemble the circuit

Assemble the circuit following the diagram EasyParkSchematics.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── EasyPark.ino       => main Arduino file
  ├── EasyParkSchematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| R1 | 10k Resistor   | 2       
| L1 | LED            | 2       
| E1 | Esp32          | 1 
| H1 | HC-SR04 Sensor | 2 
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
